In [9]:
import pandas as pd

In [10]:
tt=pd.array([1,2,3])
tt

<IntegerArray>
[1, 2, 3]
Length: 3, dtype: Int64

In [11]:
temperature_w1=pd.array([22.5,25.3,20.8,23.4,26.1,24.8,21.9])
print(temperature_w1)
print(temperature_w1.ndim)
print(temperature_w1.size)
print(temperature_w1.shape)
print(temperature_w1.dtype)

<FloatingArray>
[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9]
Length: 7, dtype: Float64
1
7
(7,)
Float64

In [12]:
print(min(temperature_w1))
print(max(temperature_w1))
print(temperature_w1.mean())

20.8
26.1
23.542857142857144

In [13]:
fahrenheit=(temperature_w1*9.5)+32
print("Coverted to Fahrenheit\n")
print(fahrenheit)

Coverted to Fahrenheit

<FloatingArray>
[            245.75,             272.35,              229.6,
 254.29999999999998, 279.95000000000005,              267.6,
 240.04999999999998]
Length: 7, dtype: Float64

In [14]:
import numpy as np

In [15]:
temperatures=np.array([[22.5,25.3,20.8,23.4,26.1,24.8,21.9],[19.2,22.5,21.3,24.0,23.5,22.8,20.1]])
temperatures

array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
       [19.2, 22.5, 21.3, 24. , 23.5, 22.8, 20.1]])

In [16]:
print(temperatures)
print(temperatures.ndim)
print(temperatures.size)
print(temperatures.shape)
print(temperatures.dtype)

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]
2
14
(2, 7)
float64

In [17]:
print("temperature in weekdays")
print(temperatures[0:6,1:6])
print("temperature in weekend  ")
print(temperatures[0:,5:])

temperature in weekdays
[[25.3 20.8 23.4 26.1 24.8]
 [22.5 21.3 24.  23.5 22.8]]
temperature in weekend
[[24.8 21.9]
 [22.8 20.1]]

Pandas

In [18]:
marks=pd.Series([95,92,89,85,80],index=["Rank1","Rank2","Rank3","Rank4","Rank5"])
print(marks.iloc[0])
print(marks.loc[["Rank1","Rank2","Rank3"]])
print(marks.iloc[2])
print(marks[marks>90])
drop.iloc["Rank5"]
marks.loc["Rank1"]=100
cgpa=marks/10
print("CGPA\n",cgpa)

marks

95
Rank1    95
Rank2    92
Rank3    89
dtype: int64
89
Rank1    95
Rank2    92
dtype: int64

NameError: name 'drop' is not defined

Pandas DataFrame

In [ ]:
transactions={
    "TransactionId":[101,102,103,104,105,106,107,108,109,110],
     "ProductCategory":["Electronics","Clothing","Electronics","furniture","Clothing","Electronics","Furniture","Clothing","Furniture","Elctronics"],
     "Region":["North","South","North","East","West","North","East","West","South","North"],
     "Amount":[200,150,300,450,200,250,300,180,350,400],
     
}
TT=pd.DataFrame(transactions)
TT
print("Last 5 transaction:\n",TT.tail(5))
print("First 5 Transaction\n",TT.head(5))
print("Size",TT.size)
print("Shape",TT.shape)
print("Dimention",TT.ndim)

Lats 5 transaction:
    TransactionId ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110      Elctronics  North     400
First 5 Transaction
    TransactionId ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       furniture   East     450
4            105        Clothing   West     200
Size 40
Shape (10, 4)
Dimention 2

In [ ]:
TT.loc["ProductCategory":"Amount"]

Empty DataFrame
Columns: [TransactionId, ProductCategory, Region, Amount]
Index: []

In [ ]:

TT[["ProductCategory","Amount"]]

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9      Elctronics     400

In [ ]:
TT[(TT["Amount"]>200) & (TT["Region"]=="North")]

   TransactionId ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110      Elctronics  North     400

In [ ]:
TT["ProductCategory"].value_counts()

ProductCategory
Electronics    3
Clothing       3
Furniture      2
furniture      1
Elctronics     1
Name: count, dtype: int64

In [ ]:
TT.groupby("Region").agg({
    "Amount":"mean"
}
)

        Amount
Region
East     375.0
North    287.5
South    250.0
West     190.0

Manipulating Data Frame

In [ ]:
TT["Discount"]=TT["Amount"]*10/100
TT

   TransactionId ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     150      15.0
2            103     Electronics  North     300      30.0
3            104       furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110      Elctronics  North     400      40.0

NameError: name 'drop' is not defined